language: shell

services:
  - docker

env:
  global:
    - TEST_CMD='echo simulated test!'
    - SSH_KEY_TYPES='rsa,dsa,ecdsa'
    - DEPLOY_ARTIFACTS_PATH='artifacts'
    - DEPLOY_ROOT_DIR='/srv'
    - REPOSITORY="$(basename $TRAVIS_REPO_SLUG)"
    - BRANCH="${TRAVIS_BRANCH}"
    - BETA_BRANCH='develop'
    - DOCKER_IMAGE_TAG=$(bash "${DEPLOY_ARTIFACTS_PATH}"/generate_docker_image_tag.sh)
    - DOCKER_IMAGE_NAME="${DOCKER_USERNAME}"/"${REPOSITORY}":"${DOCKER_IMAGE_TAG}"
    - ENCRYPTED_DEPLOY_KEY_PATH="deploy_key.enc"
    - _ENCRYPTED_DEPLOY_KEY_CYPHER_KEY="${encrypted_dfdcfd5172af_key}"
    - ENCRYPTED_DEPLOY_KEY_IV="${encrypted_dfdcfd5172af_iv}"
    - DOCKER_IMAGE_SHELL="sh"
    - HADOLINT_VERSION="1.17.5"
    - HADOLINT="${HOME}/hadolint"

install:
  - curl -sLo ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-$(uname -s)-$(uname -m)" && chmod 700 ${HADOLINT}

before_deploy:
  - eval "$(ssh-agent -s)"
  - bash "${DEPLOY_ARTIFACTS_PATH}"/setup_ssh.sh

script:
  - bash -c 'shopt -s globstar nullglob; shellcheck --exclude=SC2029 artifacts/*.{sh,ksh,bash}'
  - ${HADOLINT} --ignore=DL3025 Dockerfile
  - docker build --target build --tag "$REPOSITORY" .
  - docker run "$REPOSITORY" ${DOCKER_IMAGE_SHELL} -c "$TEST_CMD"

notifications:
  slack:
    rooms:
      secure: EhN4lKAg/s1Ud2uNxY53UJCC6/Wxy7RAyjA+x+5gZK2kzx9mrYj89RFh0iouwpf6EBhpiIQain
      7H/GUd/YJ6hIp8LyuBMw4iLdTsvbzlVWUc5c2FehXj7Rhyg/4tiDO5VsBeuDVIPrSRne0H/R+gcWu/eaIjXIP4gn
      xHieFUSrox/u+z9yiiTFSBO0eZ99x9KcIY2VL0ZNEv1yrcRlBgmtiXPrz2lJydOo6TGxHGtzPfcFjB8ixbC1ZssQ
      vfZEkI+oQlxAwJAvC6ct6iH7g9Yt9LnJxT8U7nMgEVUIum4GzG0R3zdFEcnbnXZgFqdxoi8t7PsWrzNCnffK41tH
      aMl+Hr6A5yTPanwUkxevyFdPWZ/6UWzyzDXwhOINOmi4oJbntMQ+45FW+QH1i15lEu/bvw9Tly6IB+8CJWmCP1dx
      ZPEp91hwDgD0F5jLOJOJ+fYP28OvK7km/oyP2KrDwJpkFrVzXhvuyABGisgXvhmxlgDrUsOYP/ndHKQ9shy1ViSd
      5s9ecGxcV7E1QSj6b/4D4ruCzlFqFFqpTIbd5gmovnsY3Cx9Vpdi5stWsj/Sh/bIT42au8G5X+F2+usmzPuH5QTK
      V41/RiEYWQtNFEVzQ4nG5H82LT7wjuTnX5IyiFKirN9m2X6MxKAZH7zLa4i51w/lNUM8NgvuRmcLN5nWc=
    on_success: never
  email: false

deploy:
  - provider: script
    script: bash "${DEPLOY_ARTIFACTS_PATH}"/docker_push.sh
    skip_cleanup: true
    on:
      all_branches: true

  - provider: script
    script: bash "${DEPLOY_ARTIFACTS_PATH}"/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
