name: 'Deploy'
description: 'Deploy Docker Compose app via SSH'
inputs:
  test:
    description: 'Test input'
    required: true
    default: 'Hello'
outputs:
  time:
    description: 'The time of the execution'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
