name: 'Deploy'
description: 'Deploy Docker Compose app via SSH'
inputs:
  deploy_server:
    description: 'The SSH-enabled server to deploy to'
    required: true
  deploy_username:
    description: 'The deploy server username to SSH with'
    required: true
  deploy_password:
    description: 'The deploy server password to SSH with'
    required: true
  deploy_root_dir:
    description: 'The deploy server root directory to create the deployed repository directory under'
    required: true
  encrypted_deploy_key_encryption_key:
    description: 'The encryption key for the deploy server SSH key'
    required: true
  path:
    description: 'The path to the directory containing your app (Docker Compose file, encrypted SSH deploy key)'
    required: false
    default: 'deploy_key.enc'
  stable_branch:
    description: 'The branch which represents the stable version of the app'
    required: false
    default: 'master'
  beta_branch:
    description: 'The branch which represents the beta version of the app'
    required: false
    default: 'develop'
  debug:
    description: 'Print extra debugging info (0 for false or 1 for true)'
    required: false
    default: 0
runs:
  using: 'docker'
  image: 'Dockerfile'

