version: '3'
services:
  echo:
    build: .
    image: "${DOCKER_USERNAME}/${REPOSITORY}:${TAG:-beta}"
    container_name: "${REPOSITORY}-${TAG:-beta}"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DEBUG=${DEBUG:-}
