name: CI
on: [push]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2029
  hadolint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
  hadolint-app:
    name: Hadolint Demo App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'app/Dockerfile'
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.29
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - name: Run Tests
        run: go test -v -coverprofile=cover.out ./...
      - name: Coverage Report
        run: gocov convert cover.out | gocov report
      - name: Line Coverage Report
        run: gocov convert cover.out | gocov annotate -
  demo-deploy-beta:
    runs-on: ubuntu-latest
    name: Deploy Beta Demo App
    if: ${{ !contains(github.ref, 'refs/tags') }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          path: 'app'
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: ./
        id: deploy
        with:
          deploy_server: ${{ secrets.deploy_server }}
          deploy_username: ${{ secrets.deploy_username }}
          deploy_root_dir: '/srv'
          ssh_key: ${{ secrets.ssh_key }}
          path: 'app'
          channel: 'beta'
          debug: ${{ secrets.actions_step_debug }}
          env_vars: 'FOO,BAR'
        env:
          FOO: ${{ secrets.FOO_BETA }}
          BAR: ${{ secrets.BAR_BETA }}
          FOO_STABLE: ${{ secrets.FOO_STABLE }}
          BAR_STABLE: ${{ secrets.BAR_STABLE }}
  demo-deploy-stable:
    runs-on: ubuntu-latest
    name: Deploy Stable Demo App
    if: ${{ contains(github.ref, 'refs/tags') }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          path: 'app'
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: ./
        id: deploy
        with:
          deploy_server: ${{ secrets.deploy_server }}
          deploy_username: ${{ secrets.deploy_username }}
          deploy_root_dir: '/srv'
          ssh_key: ${{ secrets.ssh_key }}
          path: 'app'
          channel: 'stable'
          debug: ${{ secrets.actions_step_debug }}
          env_vars: 'FOO,BAR'
        env:
          FOO: ${{ secrets.FOO_STABLE }}
          BAR: ${{ secrets.BAR_STABLE }}
