name: CI
on: [push]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2029
  hadolint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
  hadolint-app:
    name: Hadolint Demo App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'app/Dockerfile'
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Demo App
    if: ${{ !contains(github.ref, 'refs/tags') }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          path: 'app'
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        uses: ./
        id: deploy
        with:
          deploy_server: ${{ secrets.deploy_server }}
          deploy_username: ${{ secrets.deploy_username }}
          deploy_root_dir: '/srv'
          ssh_key: ${{ secrets.ssh_key }}
          path: 'app'
          beta_branch: 'ANY'
          debug: ${{ secrets.actions_step_debug }}
          env_var_prefixes: 'FOO,BAR'
        env:
          FOO_BETA: ${{ secrets.FOO_BETA }}
          BAR_BETA: ${{ secrets.BAR_BETA }}
          FOO_STABLE: ${{ secrets.FOO_STABLE }}
          BAR_STABLE: ${{ secrets.BAR_STABLE }}
