name: CI
on: [push]

env:
  go-version: "^1.15"
  python-version: "3.9"
  node-version: "14"
  container-registry: "ghcr.io"
  image-cache-path: "/tmp/.buildx-cache"
  image: ${{ github.repository }}-example

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install Prettier
        run: npm install -g prettier
      - name: Run Prettier
        run: prettier --check .
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
  hadolint-example:
    name: Hadolint Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: "example/Dockerfile"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install YAML Lint
        run: pip install yamllint
      - name: Run YAML Lint
        run: yamllint -f github --strict .
  lint-json:
    name: Lint JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install JSON Lint
        run: npm install -g jsonlint
      - name: Run JSON Lint
        run: find . -type f -name '*.json' -exec jsonlint --quiet --compact {} \;
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Get Dependencies
        run: |
          go mod download
          go get github.com/axw/gocov/gocov
      - name: Run Tests
        run: go test -v -coverprofile=cover.out ./...
      - name: Coverage Report
        run: gocov convert cover.out | gocov report
      - name: Line Coverage Report
        run: gocov convert cover.out | gocov annotate -
  image:
    name: Image
    runs-on: ubuntu-latest
    needs: [lint, test, hadolint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Image Metadata
        id: image-metadata
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.container-registry }}/${{ github.repository }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Cache Image Layers
        uses: actions/cache@v2
        env:
          base-key: ${{ runner.os }}-build-docker-buildx
        with:
          path: ${{ env.image-cache-path }}
          key: ${{ env.base-key }}-${{ github.sha }}
          restore-keys: |
            ${{ env.base-key }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.container-registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push to GitHub Container Registry
        id: image-build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}
          cache-from: type=local,src=${{ env.image-cache-path }}
          cache-to: type=local,dest=${{ env.image-cache-path }},mode=max
  image-example:
    name: Example Image
    runs-on: ubuntu-latest
    needs: [lint, test, hadolint-example]
    outputs:
      digest: ${{ steps.image-build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Image Metadata
        id: image-metadata
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.container-registry }}/${{ env.image }}
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Cache Image Layers
        uses: actions/cache@v2
        env:
          base-key: ${{ runner.os }}-build-docker-buildx-example
        with:
          path: ${{ env.image-cache-path }}
          key: ${{ env.base-key }}-${{ github.sha }}
          restore-keys: |
            ${{ env.base-key }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.container-registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push to GitHub Container Registry
        id: image-build
        uses: docker/build-push-action@v2
        with:
          context: "example"
          file: "example/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outpus.labels }}
          cache-from: type=local,src=${{ env.image-cache-path }}
          cache-to: type=local,dest=${{ env.image-cache-path }},mode=max
  deploy-example:
    name: Deploy Example
    runs-on: ubuntu-latest
    needs: [image-example, lint-yaml, lint-json]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./
        env:
          SAD_REGISTRY: ${{ env.container-registry }}
          SAD_IMAGE: ${{ env.image }}
          SAD_SERVER: ${{ secrets.SERVER }}
          SAD_USERNAME: ${{ secrets.USERNAME }}
          SAD_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SAD_CHANNEL: "beta"
          SAD_DIGEST: ${{ needs.image-example.outputs.digest }}
          SAD_DEPLOY_FOO: ${{ secrets.FOO }}
          SAD_DEPLOY_BAR: ${{ secrets.BAR }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, lint-yaml, lint-json, test]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
