name: CI
on: [push]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2029
  hadolint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
  hadolint-app:
    name: Hadolint Demo App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'app/Dockerfile'
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.29
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Get Dependencies
        run: |
          go mod download
          go get github.com/axw/gocov/gocov
      - name: Run Tests
        run: go test -v -coverprofile=cover.out ./...
      - name: Coverage Report
        run: gocov convert cover.out | gocov report
      - name: Line Coverage Report
        run: gocov convert cover.out | gocov annotate -
  deploy-example:
    runs-on: ubuntu-latest
    name: Deploy Example App
    needs: [go-lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE="${{ format('{0}-{1}', github.repository, 'example')}}"
          VERSION='latest'
          TAGS="$DOCKER_IMAGE:$VERSION"
          CHANNEL='stable'
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=channel::${CHANNEL}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: 'app'
          file: 'app/Dockerfile'
          tags: ${{ steps.prep.outputs.tags }}
      - name: Deploy
        uses: ./
        id: deploy
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SAD_REPOSITORY: ${{ steps.prep.outputs.docker_image }}
          SAD_SERVER: ${{ secrets.SERVER }}
          SAD_USERNAME: ${{ secrets.USERNAME }}
          SAD_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SAD_CHANNEL: ${{ steps.prep.outputs.channel }}
          SAD_DIGEST: ${{ steps.docker_build.outputs.digest }}
          SAD_DEPLOY_FOO: ${{ secrets.FOO }}
          SAD_DEPLOY_BAR: ${{ secrets.BAR }}
