name: Deploy
on: [push]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          push: false
          path: 'app'
          tag_with_ref: true
      - name: Deploy
        uses: ./
        id: deploy
        with:
          deploy_server: ''
          deploy_username: ''
          deploy_password: ''
          deploy_root_dir: '/srv'
          encrypted_deploy_key_encryption_key: ${{ secrets.encrypted_deploy_key_encryption_key }}
          path: 'app'
          debug: 1
